# GitHub repository
owner: CarlosYazid
repo: upptime-home

sites:
  - name: Sitio Web
    url: https://carlospadilla.co

  - name: WWW
    url: https://www.carlospadilla.co

status-website:
  # Dominio personalizado
  cname: status.carlospadilla.co

  # Usa el favicon de tu sitio como logo
  logoUrl: https://carlospadilla.co/favicon.ico

  name: Carlos Padilla Status

  introTitle: "Estado de los servicios"

  introMessage: >
    Monitoreo automático de disponibilidad y tiempo de respuesta
    de los servicios de Carlos Padilla.

  navbar:
    - title: Estado
      href: /

    - title: Sitio Web
      href: https://carlospadilla.co

    - title: GitHub
      href: https://github.com/CarlosYazid/upptime-home
